FS-1113-one-sub-crit-flow-to-score
communitiesuk/funding-service-design-assessment pull request #24
Opened 2022-07-18 16:33 UTC by gio-karunakaran

Question page
<img width="1792" alt="Screenshot 2022-07-22 at 09 56 29" src="https://user-images.githubusercontent.com/80714392/180403352-4bf8278d-4e31-4bc6-9370-a94f17340a72.png">

Summary page
<img width="1792" alt="Screenshot 2022-07-23 at 10 10 05" src="https://user-images.githubusercontent.com/80714392/180598860-90e7b9ff-68e2-4e2e-93a5-8bb464f946ce.png">

2022-07-22 08:02 UTC, Adam-W1 commented on app/assess/routes.py
> +    # data_dict functionality to be reviwed or deleted by Gio
does this need looking at before merge 👀

2022-07-26 15:32 UTC, SentientHousePlant requested changes

2022-07-26 15:32 UTC, SentientHousePlant commented on app/assess/data.py
>      print(response.content)
🚨

2022-07-26 15:32 UTC, SentientHousePlant commented on app/assess/models/assessment_flow.py
> +class AssessmentFlow:
💯 Lovely abstraction, nice to see advanced use of dataclasees.

2022-07-26 15:32 UTC, SentientHousePlant commented on app/assess/models/assessment_flow.py
> +            fields=AssessmentFlow.get_fields(assessment_json, page_index),
⛏️ Maybe these could be moved into variables in this function for better readability?

2022-07-26 15:32 UTC, SentientHousePlant commented on app/assess/models/assessment_flow.py
> +        for q in get_questions:
⛏️ For question?

2022-07-26 15:32 UTC, SentientHousePlant commented on app/assess/templates/macros/scores.html
> +                </details>
🤔 If this summary in details is used a lot then it could be a macro

2022-07-26 15:32 UTC, SentientHousePlant commented on app/static/src/scss/assessment_flow.scss
> +    background-color: #f3f2f1;
🤔 There is govuk sass variables you can use here. Please see https://sass-lang.com/documentation/variables and https://design-system.service.gov.uk/styles/colour/

2023-04-21 09:57 UTC, closed without merging