add functions for feedback export
communitiesuk/funding-service-design-assessment pull request #422
Opened 2023-09-21 10:49 UTC by RamuniN

_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_

### Change description
_A brief description of the pull request_

- [ ] Unit tests and other appropriate tests added or updated
- [ ] README and other documentation has been updated / added (if needed)
- [ ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
_If manual testing is needed, give suggested testing steps_

### Screenshots of UI changes (if applicable)

2023-09-25 11:11 UTC, srh-sloan requested changes
Good start but needs some error handling pls

2023-09-25 11:11 UTC, srh-sloan commented on tests/test_routes.py
> +                    feedback_export_href="/assess/feedback_export/TF/tr",
Need some unit tests that check whether the link is displayed or not, and also check error handling in `routes.py` for if application store is unavailable.

2023-09-26 08:10 UTC, RamuniN commented
@srh-sloan Implemented the suggested changes. Can you review again ?

2023-09-26 09:46 UTC, srh-sloan requested changes
One more comment, but otherwise nice 👍

2023-09-26 09:46 UTC, srh-sloan commented on app/blueprints/assessments/routes.py
> +        )
Still needs an `else`

2023-09-26 09:46 UTC, srh-sloan commented on tests/test_routes.py
> +            assert "Assessment Tracker Export" in all_exports_links[-1].text
Nice 👍

2023-09-26 10:09 UTC, RamuniN commented on app/blueprints/assessments/routes.py
> +        )
Done

2023-09-26 10:22 UTC, srh-sloan approved these changes

2023-09-26 10:23 UTC, merged