Bau check for null
communitiesuk/funding-service-design-assessment pull request #44
Opened 2022-10-06 14:59 UTC by srh-sloan

Added null check around date_submitted from application

2022-10-10 16:41 UTC, harryyo requested changes
Great, just a comment

2022-10-10 16:41 UTC, harryyo commented on config/envs/development.py
> +    # ASSESSMENT_STORE_API_HOST = "https://funding-service-design-assessment-store-dev.london.cloudapps.digital"  # noqa
Can this go altogether?

2022-10-11 10:04 UTC, srh-sloan commented on config/envs/development.py
> +    # ASSESSMENT_STORE_API_HOST = "https://funding-service-design-assessment-store-dev.london.cloudapps.digital"  # noqa
Yes, good spot!

2022-10-11 11:41 UTC, harryyo approved these changes

2022-10-11 12:13 UTC, merged